# Generated by Django 4.0.5 on 2022-06-12 21:59

from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='images', validators=[polls.validators.validate_file_extension], verbose_name='image'),
        ),
    ]
