# Generated by Django 4.0.5 on 2022-06-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Images'},
        ),
    ]
