# Generated by Django 4.0.5 on 2022-06-18 13:42

from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_imagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='images', validators=[polls.validators.validate_file_extension], verbose_name='Файл'),
        ),
    ]
